spring.application.name=tourisminformation
server.port=8081

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

app.cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://localhost
